
[SETTINGS]
$enhanced_edit          all 
$SEARCH_OBJECT  = dbms_first
$SEARCH_DESCRIPTOR = dbms_first
$variation = SYSTEM_LIBRARY
$RESOURCES_OUTPUT = rso

[RESOURCES]
.\rso
usys:uidf.uar

[FILES]
usys:idf.aps            usysuniface:components\idf.aps
usys:uu*.frm            usysuniface:components\uu*.frm
usys:uu*.svc            usysuniface:components\uu*.svc
common:uu*.frm          usys:..\components\uu*.frm
common:uu*.svc          usys:..\components\uu*.svc
common:ur*.svc          usys:..\components\ur*.svc
usys:*.xml              usysuniface:misc\*.xml
*.cptlist		.\lst\*.*
 
[PROXY_SETTINGS]
$BYPASS = *

[DRIVER_SETTINGS]
SLE     U1.0
MSS	U5.0
USYS$SLE_PARAMS create db = on, identifiers = quoted 
USYS$MSS_PARAMS = hs:on, ids:quoted, procs:off,locktime:360, keysetcursor:on,checks:off
 

[PATHS]
 

; Path to the SQLite database for the Uniface Repository:
$DBMS        SLE:.\dbms\usys.db
; Path to the SQLite database for User defined data:
$DBMS_DEF    SLE:.\dbms\userdata.db

$SYS    $DBMS
$UUU    $DBMS
$IDF    $DBMS
$DEF    $DBMS_DEF


[ENTITIES]


[USER_3GL]
.\bin\metaphone(metaphone)